--- 
jobs: 
  pull-request: 
    if: "github.event.pull_request.merged && steps.branch-name.outputs.head_ref_branch != 'canary' && steps.branch-name.outputs.head_ref_branch != 'qa' && steps.branch-name.outputs.head_ref_branch != 'dev'"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: checkout
        uses: actions/checkout@v2
      - 
        if: "${{ steps.branch-name.outputs.ref_branch == 'master' }}"
        name: backport-to-canary
        uses: repo-sync/pull-request@v2
        with: 
          destination_branch: canary
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          pr_title: "[Backport ${steps.branch-name.outputs.head_ref_branch}] to canary"
      - 
        if: "${{ steps.branch-name.outputs.ref_branch == 'canary' }}"
        name: backport-to-qa
        uses: repo-sync/pull-request@v2
        with: 
          destination_branch: qa
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          pr_title: "[Backport ${steps.branch-name.outputs.head_ref_branch}] to qa"
      - 
        if: "${{ steps.branch-name.outputs.ref_branch == 'qa' }}"
        name: backport-to-dev
        uses: repo-sync/pull-request@v2
        with: 
          destination_branch: develop
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          pr_title: "[Backport ${steps.branch-name.outputs.head_ref_branch}] to develop"
name: pull-request
true: 
  push: 
    branches: 
      - master
      - canary
      - qa