name: pull-request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
    - master
    - qa
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: checkout
      uses: actions/checkout@v2
    - name: pull-request
      if: ${{ steps.branch-name.outputs.head_ref_branch != 'develop' && steps.branch-name.outputs.head_ref_branch != 'qa' }}
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: develop
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Pulling ${{ steps.branch-name.outputs.head_ref_branch }} into master"
