name: pull-request
'on':
  push:
    branches:
      - master
      - canary
      - qa
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: validation
        run: |
          if ${{ (steps.branch-name.outputs.current_branch != 'master') &&
          (steps.branch-name.outputs.current_branch != 'canary') &&
          (steps.branch-name.outputs.current_branch != 'qa') &&
          (steps.branch-name.outputs.current_branch != 'develop') }}; then
              echo "NEED=true" >> "$GITHUB_ENV"
          else
              echo "NEED=false" >> "$GITHUB_ENV"
          fi     
      - name: checkout
        if: env.NEED == 'true'
        uses: actions/checkout@v2
      - name: create new branch
        if: env.NEED == 'true'
        uses: peterjgrainger/action-create-branch@v2.2.0
        run: echo FOO=foobar--$(date +%s) >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: backport/${{ env.FOO }}
      - name: backport-to-canary
        if: ${{ steps.branch-name.outputs.ref_branch == 'master' && env.NEED == 'true' }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: backport/release-candidate
          destination_branch: canary
          github_token: ${{ github.token }}
          pr_title: >-
             [Backport ${{ steps.branch-name.outputs.ref_branch }}] to
              canary
      - name: backport-to-qa
        if: ${{ steps.branch-name.outputs.ref_branch == 'canary' && env.NEED == 'true' }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: backport/release-candidate
          destination_branch: qa
          github_token: ${{ github.token }}
          pr_title: >-
            [Backport ${{ steps.branch-name.outputs.ref_branch }}] to 
             qa
      - name: backport-to-dev
        if: ${{ steps.branch-name.outputs.ref_branch == 'qa' && env.NEED == 'true' }}
        uses: repo-sync/pull-request@v2
        with:
          source_branch: backport/release-candidate
          destination_branch: develop
          github_token: ${{ github.token }}
          pr_title: >-
            [Backport ${{ steps.branch-name.outputs.ref_branch }}] to 
             develop